[parity]
chain = "config/spec.json"
base_path = "parity_data2"

[network]
port = 40303
discovery = true
reserved_peers="config/reserved_peers"

[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_set", "parity_pubsub", "personal", "traces"]
port = 9545

[websockets]
disable = true

[ipc]
disable = true

[secretstore]
disable = true

[account]
unlock = ["0x1a22d96792666863f429a85623e6d4ca173d26ab"]
password = ["config/pwd"]

[mining]
force_sealing = true
min_gas_price = 1000000000
engine_signer = "0x1a22d96792666863f429a85623e6d4ca173d26ab"
reseal_on_txs = "none"
