#!/bin/bash

#set -x
set -u
set -e

function kill_process {
	if lsof -t -i:$1 > /dev/null
	then
		kill -9 $(lsof -t -i:${1})
	fi
}

kill_process 8545
kill_process 9545
kill_process 9546
kill_process 9547
